const messages = {
    en: {
        common: {
            submit: "Submit",
            yes: "Yes",
            no: "No",
            save: "Save",
            cancel: "Cancel",
            upload_record: "Upload Record",
        },
        auth: {
            login: "Login",
            register: "Register",
            logout: "Logout",
            profile: "Profile",
            account: "Account",
            in_game_account: "In-game Account",
            username: "Username",
            password: "Password",
            confirm_password: "Confirm Password",
            email: "Email Address",
            upload_token: "Upload Token",
            qq_number: "QQ Number",
            uuid: "In-game UUID",
            anonymous_probe: "Permit Anonymous Query",
        },
        term: {
            b50: "Best 50",
            records: "Play Records",
            best_records: "Best Records",
            song_level_id: "Level ID",
            song_levels: "Song Levels",
            single_info: "Single Info",
            title: "Title",
            artist: "Composer",
            level_design: "Level Design",
            cover: "Cover",
            illustrator: "Illustrator",
            version: "Version",
            b35orb15: "New / Old Version",
            b35: "Old version",
            b15: "New version",
            level: "Level",
            fitting_level: "Fitting Level",
            difficulty: "Difficulty",
            album: "Album",
            genre: "Genre",
            length: "Length",
            notes: "Notes",
            score: "Score",
            replace: "Replace the Best Record",
            upload_list: "Upload List",
        },
        message: {
            welcome: "Welcome, {username}! ",
            success_get: "Successfully get {data_name} data",
            search: "Type to search by song title",
            required: "This field is required",
            username_length: "Length should be 6 to 10",
            username_character: "Username must be consist of English characters and numbers",
            password_length: "Length should be 8 to 20",
            password_character: "Password must be consist of English characters and numbers",
            password_mismatch: "Two passwords don't match",
            register_success: "Register success",
            register_failed: "Register failed, details: ",
            login_success: "Login success",
            login_failed: "Login failed, details: ",
            get_levels_success: "Successfully get level info",
            get_levels_failed: "Failed to get level info",
            get_my_info_success: "Successfully get user profile",
            get_my_info_failed: "Failed to get user profile. Details: ",
            token_expired: "Access token has expired, please re-login",
            post_record_success: "Successfully upload record",
            post_record_failed: "Failed to upload record. Details: ",
            score_out_of_range: "Please input a score between 0 and 1010000",
            song_detail: "Song details",
            quick_upload: "Quick upload",
            add_to_upload_list: "Add to upload list",
            add_to_upload_list_success: "Successfully add to upload list",
            add_to_upload_list_failed: "Failed add to upload list, this level has already in the list"
        }
    },
    zh_cn: {
        common: {
            submit: "提交",
            yes: "是",
            no: "否",
            save: "保存",
            cancel: "取消",
            upload_record: "上传记录",
        },
        auth: {
            login: "登入",
            register: "注册",
            logout: "登出",
            profile: "个人资料",
            account: "账户",
            in_game_account: "游戏内账户",
            username: "用户名",
            password: "密码",
            confirm_password: "确认密码",
            email: "电子邮箱",
            upload_token: "上传成绩 Token",
            qq_number: "QQ 号",
            uuid: "游戏内 UUID",
            anonymous_probe: "允许匿名查询",
        },
        term: {
            b50: "Best 50",
            records: "游玩记录",
            song_level_id: "谱面 ID",
            best_records: "最佳记录",
            song_levels: "定数表",
            single_info: "单曲信息",
            title: "曲名",
            artist: "曲师",
            cover: "曲绘",
            difficulty: "难度",
            level: "定数",
            fitting_level: "拟合定数",
            level_design: "谱师",
            illustrator: "画师",
            version: "版本",
            b35orb15: "新/旧版本",
            b35: "旧版本",
            b15: "新版本",
            album: "专辑",
            genre: "流派",
            length: "曲长",
            notes: "音符数量",
            score: "分数",
            replace: "替换最佳纪录",
            upload_list: "待上传列表",
        },
        message: {
            welcome: "欢迎，{username}！",
            success_get: "成功获取 {data_name} 数据",
            search: "搜素曲名",
            required: "请输入该字段",
            username_length: "用户名长度在 6 到 10 之间",
            username_character: "用户名必须由由数字或英文字母组成",
            password_length: "密码长度在 8 到 10 之间",
            password_character: "密码必须同时包含字母和数字",
            password_mismatch: "两次输入密码不匹配",
            register_success: "注册成功",
            register_failed: "注册失败，详情：",
            login_success: "登入成功",
            login_failed: "登入失败，详情： ",
            get_my_info_success: "成功获取个人资料",
            get_my_info_failed: "获取个人资料失败，详情：",
            token_expired: "认证信息已过期，尝试重新登入",
            get_levels_success: "成功获取谱面信息",
            get_levels_failed: "获取铺面信息失败，详情：",
            post_record_success: "上传成绩成功",
            post_record_failed: "上传成绩失败，详情：",
            score_out_of_range: "请输入 0 到 1010000 间的分数",
            song_detail: "查看歌曲详情",
            quick_upload: "快捷上传",
            add_to_upload_list: "添加到待上传列表",
            add_to_upload_list_success: "成功加入待上传列表",
            add_to_upload_list_failed: "加入待上传列表失败，该谱面已经存在"
        }
    }
}

export default messages;